# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86206ab5e2867ee3f0eb2b65a76d3f26ea2ff902944b879a07d165d80dc52e9b5ec6dbf1de55a21bc8f3c0e98490ddaf5405ac974870efbf68cd695fb3fee24c

test:
  secret_key_base: 2de9eca6ecde38579d7332a547ce960ee1bd32a0c6ae4436dbfb15fdcbc439a255a5676aa1e69ca6183593bdeb9b08aaa2f3c17ac502009b38766f098887f85c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
